# _config.yml

# required, replace with your own information -----
title: Sabrina's Blog
author: Sabrina Gramuglia
description: > 
  A portfolio for my schoolwork
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

